name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows to run workflow manually
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ github.actor }}
    steps:
      -
        name: echo shit
        run: echo "$GITHUB_USERNAME"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: "linux/arm64,linux/amd64"
          push: true
          tags: scui2/modulescanner:latest
        env:
          GITHUB_USERNAME: ${{ github.actor }}
